name: xtts_flutter
description: XTTS client
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path_provider: ^2.0.11
  file_picker: ^5.2.2
  record: ^4.4.0
  audioplayers: ^6.5.1

flutter:
  uses-material-design: true
